"""Phase 2 keyframe-image POC.

Runs exp_144 PhasedReActAgent on selected video tasks, but suppresses raw
video_url and attaches extracted unique keyframes as image_url parts in the
first user message.

This script expects keyframes generated by:
  uv run python scripts/extract_video_keyframes_poc.py --tasks task_1,task_25,task_31
"""
from __future__ import annotations

import argparse
import base64
import csv
import json
import os
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from dotenv import load_dotenv

load_dotenv(REPO / ".env")

# Strongest current clean setting, plus EXP144_VIDEO=1 to suppress raw video
# attachment in PhasedReActAgent.
os.environ.setdefault("EXP144_ANSWER_SHAPE", "1")
os.environ.setdefault("EXP144_PROSE", "1")
os.environ.setdefault("EXP144_VIDEO", "1")

from kobushi_core.benchmark.dataset import DABenchPublicDataset
from kobushi_core.model import ModelMessage, OpenAIModelAdapter
from experiments.exp_144_modality.adaptive_vote import adaptive_vote
from experiments.exp_144_modality.math_advisor import generate_formula
from experiments.exp_144_modality.phased_agent import PhasedAgentConfig, PhasedReActAgent
from experiments.exp_144_modality.preamble import build_preamble
from experiments.exp_144_modality.prompt import build_observation_prompt, build_phased_system_prompt, build_task_prompt
from experiments.exp_144_modality.tools.registry import create_default_tool_registry


DATA_ROOT = REPO / "data" / "phase2_demo" / "demo_samples_phase2"
INPUT_ROOT = DATA_ROOT / "input"
GOLD_ROOT = DATA_ROOT / "output"
DEFAULT_KEYFRAME_ROOT = REPO / "artifacts" / "video_keyframes_poc"
MAX_STEPS = 64


KEYFRAME_NOTE = """# [VIDEO] keyframes — extracted unique dashboard screens
The raw briefing video has been converted into timestamped keyframe images and
attached to this first user message. Use these keyframes as the authoritative
source for video-defined criteria: selected fields, operators, thresholds,
time periods, ranking cutoffs, boundary samples, and displayed answers.
Prefer explicit configuration screens over later queue/status summary screens
when they conflict.
"""


def make_model(temp: float = 0.6) -> OpenAIModelAdapter:
    return OpenAIModelAdapter(
        model="qwen3.5-35b-a3b",
        api_base=os.environ.get("AGENT_API_BASE", ""),
        api_key=os.environ.get("AGENT_API_KEY", ""),
        temperature=temp,
        extra_headers={
            "CF-Access-Client-Id": os.environ.get("CF_ACCESS_CLIENT_ID", ""),
            "CF-Access-Client-Secret": os.environ.get("CF_ACCESS_CLIENT_SECRET", ""),
        },
    )


def official_score(pred_csv: Path, gold_csv: Path) -> float:
    from kobushi_core.eval.csv_compare import EvaluationOptions, _evaluate_task

    if not gold_csv.is_file():
        return 0.0
    try:
        ev = _evaluate_task(
            task_id=pred_csv.parent.name,
            prediction_path=pred_csv,
            gold_path=gold_csv,
            options=EvaluationOptions(),
        )
        return float(ev.official_score_lambda_0_5)
    except Exception as exc:
        print(f"  [score err] {exc}", flush=True)
        return 0.0


def keyframes_for_task(task_id: str, root: Path, max_images: int) -> list[Path]:
    frames = sorted((root / task_id / "keyframes").glob("*.jpg"))
    if not frames:
        raise FileNotFoundError(f"No keyframes for {task_id}: {root / task_id / 'keyframes'}")
    if len(frames) <= max_images:
        return frames
    # Keep uniform coverage over unique frames.
    if max_images <= 1:
        return [frames[0]]
    idxs = [round(i * (len(frames) - 1) / (max_images - 1)) for i in range(max_images)]
    return [frames[i] for i in sorted(set(idxs))]


def image_part(path: Path) -> dict:
    b64 = base64.b64encode(path.read_bytes()).decode()
    return {
        "type": "image_url",
        "image_url": {"url": f"data:image/jpeg;base64,{b64}"},
    }


class KeyframePhasedAgent(PhasedReActAgent):
    def __init__(self, *, keyframes: list[Path], **kwargs) -> None:
        super().__init__(**kwargs)
        self.keyframes = list(keyframes)

    def _build_messages(self, task, state, phase):
        system_content = build_phased_system_prompt(phase, self.tools.describe_for_prompt())
        messages = [ModelMessage(role="system", content=system_content)]
        task_prompt = build_task_prompt(task)
        if self.preamble:
            task_prompt = f"{self.preamble}\n\n---\n\n{task_prompt}"

        content = [{"type": "text", "text": task_prompt}]
        for p in self.keyframes:
            content.append({"type": "text", "text": f"Keyframe: {p.name}"})
            content.append(image_part(p))
        messages.append(ModelMessage(role="user", content=content))

        for step in state.steps:
            messages.append(ModelMessage(role="assistant", content=step.raw_response))
            messages.append(ModelMessage(role="user", content=build_observation_prompt(step.observation)))
        return messages


def run_one(tid: str, out_dir: Path, args) -> dict:
    t0 = time.time()
    ds = DABenchPublicDataset(root_dir=INPUT_ROOT)
    task = ds.get_task(tid)
    task_dir = out_dir / tid
    task_dir.mkdir(parents=True, exist_ok=True)

    keyframes = keyframes_for_task(tid, Path(args.keyframe_root), args.max_images)
    (task_dir / "keyframes_used.txt").write_text(
        "\n".join(str(p) for p in keyframes), encoding="utf-8"
    )

    formula = "NO_CALC"
    try:
        formula = generate_formula(task.question)
    except Exception as exc:
        formula = f"NO_CALC ({exc})"
    (task_dir / "formula.txt").write_text(formula, encoding="utf-8")

    preamble = build_preamble(task).text
    inventory = "\n".join(f"- {p.name}" for p in keyframes)
    injected = f"{KEYFRAME_NOTE}\nAttached keyframes:\n{inventory}\n\n---\n\n{preamble}"
    if formula and not formula.strip().upper().startswith("NO_CALC"):
        injected = (
            "# MATH FORMULA HINT (= expert calculation guide)\n"
            f"  {formula}\n\n"
            "Follow this aggregation/division/filter structure EXACTLY.\n\n"
        ) + injected

    model = make_model(args.temperature)
    tools = create_default_tool_registry(
        auditor_model=model,
        question_provider=lambda: task.question,
        context_dir=task.context_dir,
    )
    agent = KeyframePhasedAgent(
        model=model,
        tools=tools,
        config=PhasedAgentConfig(max_steps=MAX_STEPS, min_explore_queries=3),
        preamble=injected,
        keyframes=keyframes,
    )
    result = agent.run(task)
    trace = {
        "answer": (
            {"columns": list(result.answer.columns), "rows": [list(r) for r in result.answer.rows]}
            if result.answer
            else None
        ),
        "failure_reason": result.failure_reason,
        "steps": [
            {
                "i": i,
                "action": s.action,
                "action_input": s.action_input,
                "thought": (s.thought or "")[:2200],
                "observation_ok": s.observation.get("ok") if isinstance(s.observation, dict) else None,
                "observation_content_preview": str(
                    s.observation.get("content") if isinstance(s.observation, dict) else s.observation
                )[:700],
            }
            for i, s in enumerate(result.steps)
        ],
    }
    (task_dir / "trace.json").write_text(json.dumps(trace, ensure_ascii=False, indent=2, default=str), encoding="utf-8")

    if not result.answer or not result.answer.rows:
        return {"tid": tid, "score": 0.0, "n_ok": 0, "elapsed": time.time() - t0}

    voted = adaptive_vote([result.answer])
    pred = task_dir / "prediction.csv"
    with pred.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(voted.columns)
        writer.writerows(voted.rows)

    return {
        "tid": tid,
        "score": official_score(pred, GOLD_ROOT / tid / "gold.csv"),
        "n_ok": 1,
        "cols": list(voted.columns),
        "elapsed": time.time() - t0,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tasks", required=True, help="comma-separated task ids")
    parser.add_argument("--keyframe-root", default=str(DEFAULT_KEYFRAME_ROOT))
    parser.add_argument("--max-images", type=int, default=18)
    parser.add_argument("--temperature", type=float, default=0.6)
    args = parser.parse_args()

    task_ids = [t.strip() for t in args.tasks.split(",") if t.strip()]
    runs = REPO / "artifacts" / "runs"
    runs.mkdir(parents=True, exist_ok=True)
    i = 1
    while (runs / f"exp_144_keyframe_poc_{i:03d}").exists():
        i += 1
    out_dir = runs / f"exp_144_keyframe_poc_{i:03d}"
    out_dir.mkdir(parents=True)

    print(f"=== keyframe POC → {out_dir.name} ===", flush=True)
    print(
        f"tasks={task_ids}, keyframe_root={args.keyframe_root}, max_images={args.max_images}, "
        f"flags answer_shape={os.environ.get('EXP144_ANSWER_SHAPE')} "
        f"prose={os.environ.get('EXP144_PROSE')} video={os.environ.get('EXP144_VIDEO')}",
        flush=True,
    )

    results = []
    for k, tid in enumerate(task_ids, 1):
        try:
            r = run_one(tid, out_dir, args)
        except Exception as exc:
            r = {"tid": tid, "score": 0.0, "n_ok": 0, "error": str(exc)[:300], "elapsed": 0.0}
        results.append(r)
        mark = "✓" if r.get("score", 0.0) >= 0.999 else "✗"
        print(
            f"[{k:2d}/{len(task_ids)}] {mark} {tid:<8} score={r.get('score', 0.0):.3f} "
            f"n_ok={r.get('n_ok', 0)} t={r.get('elapsed', 0.0):.0f}s {r.get('error', '')[:100]}",
            flush=True,
        )

    mean = sum(float(r.get("score", 0.0)) for r in results) / len(results) if results else 0.0
    summary = {
        "tag": "keyframe_poc",
        "n_tasks": len(results),
        "mean_score": mean,
        "n_perfect": sum(float(r.get("score", 0.0)) >= 0.999 for r in results),
        "n_zero": sum(float(r.get("score", 0.0)) < 0.01 for r in results),
        "config": {
            "keyframe_root": args.keyframe_root,
            "max_images": args.max_images,
            "temperature": args.temperature,
            "max_steps": MAX_STEPS,
            "flags": {
                "EXP144_ANSWER_SHAPE": os.environ.get("EXP144_ANSWER_SHAPE"),
                "EXP144_PROSE": os.environ.get("EXP144_PROSE"),
                "EXP144_VIDEO": os.environ.get("EXP144_VIDEO"),
            },
        },
        "results": results,
    }
    (out_dir / "summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"=== DONE mean={mean:.4f} saved {out_dir / 'summary.json'} ===", flush=True)


if __name__ == "__main__":
    main()
