"""Phase 2 video-ASR POC.

Runs the exp_144 phased agent on selected video tasks, but injects a CPU ASR
transcript of context/video/briefing.mp4 into the preamble.

Default flags match the current strongest clean setting:
  EXP144_ANSWER_SHAPE=1
  EXP144_PROSE=1
  EXP144_VIDEO=0  (= keep raw video attached; add ASR text as extra context)

Run with:
  UV_CACHE_DIR=/tmp/uv-cache HF_HOME=/tmp/hf-home \
  uv run --with faster-whisper python scripts/phase2_video_asr_poc.py \
    --tasks task_1,task_25,task_31 --asr-model small
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from dotenv import load_dotenv

load_dotenv(REPO / ".env")

# Match exp_144_answer_shape_prose unless caller explicitly overrides.
os.environ.setdefault("EXP144_ANSWER_SHAPE", "1")
os.environ.setdefault("EXP144_PROSE", "1")
os.environ.setdefault("EXP144_VIDEO", "0")

from kobushi_core.benchmark.dataset import DABenchPublicDataset
from kobushi_core.model import OpenAIModelAdapter
from experiments.exp_144_modality.adaptive_vote import adaptive_vote
from experiments.exp_144_modality.math_advisor import generate_formula
from experiments.exp_144_modality.phased_agent import PhasedAgentConfig, PhasedReActAgent
from experiments.exp_144_modality.preamble import build_preamble
from experiments.exp_144_modality.tools.registry import create_default_tool_registry


DATA_ROOT = REPO / "data" / "phase2_demo" / "demo_samples_phase2"
INPUT_ROOT = DATA_ROOT / "input"
GOLD_ROOT = DATA_ROOT / "output"
MAX_STEPS = 64

ASR_NOTE = """# [VIDEO] audio transcript — CPU ASR
The briefing video has an audio track. The transcript below was generated by
CPU ASR and may contain errors in exact numbers, dates, IDs, and domain terms.
Use it to identify spoken criteria and workflow hints, then verify exact values
against on-screen text / database evidence before answering.
"""

ZH_ASR_PROMPT = (
    "以下是金融、医疗或数据看板语音。常见术语：流通A股股本、流通股、股本、筛选、"
    "准入线、统计年份、二级行业、行业分类、字段、批次、导出、队列、加载、"
    "视图、口径、公司代码、净资产、监控、配置、边界样本、基金、患者。"
)

EN_ASR_PROMPT = (
    "This is an analytics dashboard briefing. Common terms include configuration, "
    "criteria, threshold, date range, scope, boundary sample, export, net foreign "
    "assets, M2, patient, procedure, fund, industry, and company code."
)


def make_model(temp: float = 0.6) -> OpenAIModelAdapter:
    return OpenAIModelAdapter(
        model="qwen3.5-35b-a3b",
        api_base=os.environ.get("AGENT_API_BASE", ""),
        api_key=os.environ.get("AGENT_API_KEY", ""),
        temperature=temp,
        extra_headers={
            "CF-Access-Client-Id": os.environ.get("CF_ACCESS_CLIENT_ID", ""),
            "CF-Access-Client-Secret": os.environ.get("CF_ACCESS_CLIENT_SECRET", ""),
        },
    )


def official_score(pred_csv: Path, gold_csv: Path) -> float:
    from kobushi_core.eval.csv_compare import EvaluationOptions, _evaluate_task

    if not gold_csv.is_file():
        return 0.0
    try:
        ev = _evaluate_task(
            task_id=pred_csv.parent.name,
            prediction_path=pred_csv,
            gold_path=gold_csv,
            options=EvaluationOptions(),
        )
        return float(ev.official_score_lambda_0_5)
    except Exception as exc:
        print(f"  [score err] {exc}", flush=True)
        return 0.0


def has_cjk(text: str) -> bool:
    return any("\u4e00" <= ch <= "\u9fff" for ch in text)


def find_video(context_dir: Path) -> Path | None:
    for ext in ("*.mp4", "*.webm", "*.mov", "*.avi", "*.mkv"):
        hits = sorted(context_dir.glob(f"**/{ext}"))
        if hits:
            return hits[0]
    return None


def build_asr_transcript(
    *,
    whisper_model,
    video_path: Path,
    question: str,
    language: str | None,
) -> str:
    lang = language
    if lang == "auto":
        lang = None
    if lang is None:
        lang = "zh" if has_cjk(question) else None
    prompt = ZH_ASR_PROMPT if lang == "zh" else EN_ASR_PROMPT

    t0 = time.time()
    segments, info = whisper_model.transcribe(
        str(video_path),
        language=lang,
        beam_size=5,
        vad_filter=True,
        initial_prompt=prompt,
    )
    lines = [
        f"model_language={info.language} language_probability={info.language_probability:.3f} "
        f"duration={info.duration:.1f}s elapsed={time.time() - t0:.1f}s",
    ]
    for seg in segments:
        text = seg.text.strip()
        if text:
            lines.append(f"[{seg.start:05.1f}-{seg.end:05.1f}] {text}")
    return "\n".join(lines)


def run_one(tid: str, out_dir: Path, whisper_model, args) -> dict:
    t0 = time.time()
    ds = DABenchPublicDataset(root_dir=INPUT_ROOT)
    task = ds.get_task(tid)
    task_dir = out_dir / tid
    task_dir.mkdir(parents=True, exist_ok=True)

    video_path = find_video(task.context_dir)
    asr_text = ""
    if video_path is not None:
        asr_file = task_dir / "asr_transcript.txt"
        if args.reuse_asr and asr_file.exists():
            asr_text = asr_file.read_text(encoding="utf-8", errors="replace")
        else:
            asr_text = build_asr_transcript(
                whisper_model=whisper_model,
                video_path=video_path,
                question=task.question,
                language=args.language,
            )
            asr_file.write_text(asr_text, encoding="utf-8")

    if args.asr_only:
        return {
            "tid": tid,
            "score": None,
            "n_ok": 0,
            "asr_chars": len(asr_text),
            "elapsed": time.time() - t0,
        }

    formula = "NO_CALC"
    try:
        formula = generate_formula(task.question)
    except Exception as exc:
        formula = f"NO_CALC ({exc})"
    (task_dir / "formula.txt").write_text(formula, encoding="utf-8")

    m = make_model(temp=args.temperature)
    preamble = build_preamble(task)
    injected = preamble.text
    if asr_text:
        injected = f"{ASR_NOTE}\n{asr_text}\n\n---\n\n{injected}"
    if formula and not formula.strip().upper().startswith("NO_CALC"):
        injected = (
            "# MATH FORMULA HINT (= expert calculation guide)\n"
            f"  {formula}\n\n"
            "Follow this aggregation/division/filter structure EXACTLY.\n\n"
        ) + injected

    tools = create_default_tool_registry(
        auditor_model=m,
        question_provider=lambda: task.question,
        context_dir=task.context_dir,
    )
    agent = PhasedReActAgent(
        model=m,
        tools=tools,
        config=PhasedAgentConfig(max_steps=MAX_STEPS, min_explore_queries=3),
        preamble=injected,
    )
    result = agent.run(task)
    trace = {
        "answer": (
            {"columns": list(result.answer.columns), "rows": [list(r) for r in result.answer.rows]}
            if result.answer
            else None
        ),
        "failure_reason": result.failure_reason,
        "steps": [
            {
                "i": i,
                "action": s.action,
                "action_input": s.action_input,
                "thought": (s.thought or "")[:2000],
                "observation_ok": s.observation.get("ok") if isinstance(s.observation, dict) else None,
                "observation_content_preview": str(
                    s.observation.get("content") if isinstance(s.observation, dict) else s.observation
                )[:600],
            }
            for i, s in enumerate(result.steps)
        ],
    }
    (task_dir / "trace.json").write_text(json.dumps(trace, ensure_ascii=False, indent=2, default=str), encoding="utf-8")

    if not result.answer or not result.answer.rows:
        return {"tid": tid, "score": 0.0, "n_ok": 0, "elapsed": time.time() - t0}

    voted = adaptive_vote([result.answer])
    pred = task_dir / "prediction.csv"
    with pred.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(voted.columns)
        writer.writerows(voted.rows)

    score = official_score(pred, GOLD_ROOT / tid / "gold.csv")
    return {
        "tid": tid,
        "score": score,
        "n_ok": 1,
        "cols": list(voted.columns),
        "elapsed": time.time() - t0,
    }


def default_failed_video_tasks() -> list[str]:
    summary = REPO / "artifacts" / "runs" / "exp_144_answer_shape_prose_002" / "summary.json"
    video_tasks = {p.parts[-4] for p in INPUT_ROOT.glob("task_*/context/video/*.mp4")}
    if not summary.exists():
        return sorted(video_tasks, key=lambda x: int(x.split("_")[1]))
    data = json.loads(summary.read_text())
    tids = [
        r["tid"]
        for r in data.get("results", [])
        if r.get("tid") in video_tasks and float(r.get("score", 0.0)) < 0.999
    ]
    return sorted(tids, key=lambda x: int(x.split("_")[1]))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tasks", default=None, help="comma-separated task ids; default: failed video tasks in exp_144_answer_shape_prose_002")
    parser.add_argument("--asr-model", default="small", help="faster-whisper model name, e.g. tiny/base/small/medium")
    parser.add_argument("--cpu-threads", type=int, default=4)
    parser.add_argument("--language", default="auto", choices=["auto", "zh", "en"])
    parser.add_argument("--temperature", type=float, default=0.6)
    parser.add_argument("--reuse-asr", action="store_true")
    parser.add_argument("--asr-only", action="store_true", help="only generate ASR transcripts; do not call the LLM agent/API")
    args = parser.parse_args()

    if args.tasks:
        task_ids = [t.strip() for t in args.tasks.split(",") if t.strip()]
    else:
        task_ids = default_failed_video_tasks()

    runs = REPO / "artifacts" / "runs"
    runs.mkdir(parents=True, exist_ok=True)
    i = 1
    while (runs / f"exp_144_video_asr_poc_{i:03d}").exists():
        i += 1
    out_dir = runs / f"exp_144_video_asr_poc_{i:03d}"
    out_dir.mkdir(parents=True)

    from faster_whisper import WhisperModel

    print(f"=== video ASR POC → {out_dir.name} ===", flush=True)
    print(
        f"tasks={task_ids}, asr_model={args.asr_model}, cpu_threads={args.cpu_threads}, "
        f"flags answer_shape={os.environ.get('EXP144_ANSWER_SHAPE')} prose={os.environ.get('EXP144_PROSE')} "
        f"video={os.environ.get('EXP144_VIDEO')}",
        flush=True,
    )
    t_load = time.time()
    whisper_model = WhisperModel(
        args.asr_model,
        device="cpu",
        compute_type="int8",
        cpu_threads=args.cpu_threads,
    )
    print(f"loaded ASR model in {time.time() - t_load:.1f}s", flush=True)

    results = []
    for k, tid in enumerate(task_ids, 1):
        try:
            r = run_one(tid, out_dir, whisper_model, args)
        except Exception as exc:
            r = {"tid": tid, "score": 0.0, "n_ok": 0, "error": str(exc)[:300], "elapsed": 0.0}
        results.append(r)
        score_val = r.get("score")
        mark = "·" if score_val is None else ("✓" if score_val >= 0.999 else "✗")
        print(
            f"[{k:2d}/{len(task_ids)}] {mark} {tid:<8} score={score_val if score_val is not None else 'asr-only'} "
            f"n_ok={r.get('n_ok', 0)} t={r.get('elapsed', 0.0):.0f}s {r.get('error', '')[:80]}",
            flush=True,
        )

    scored = [float(r.get("score", 0.0)) for r in results if r.get("score") is not None]
    mean = sum(scored) / len(scored) if scored else None
    summary = {
        "tag": "video_asr_poc",
        "n_tasks": len(results),
        "mean_score": mean,
        "n_perfect": sum(float(r.get("score", 0.0)) >= 0.999 for r in results if r.get("score") is not None),
        "n_zero": sum(float(r.get("score", 0.0)) < 0.01 for r in results if r.get("score") is not None),
        "config": {
            "asr_only": args.asr_only,
            "asr_model": args.asr_model,
            "cpu_threads": args.cpu_threads,
            "temperature": args.temperature,
            "max_steps": MAX_STEPS,
            "flags": {
                "EXP144_ANSWER_SHAPE": os.environ.get("EXP144_ANSWER_SHAPE"),
                "EXP144_PROSE": os.environ.get("EXP144_PROSE"),
                "EXP144_VIDEO": os.environ.get("EXP144_VIDEO"),
            },
        },
        "results": results,
    }
    (out_dir / "summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    mean_text = f"{mean:.4f}" if mean is not None else "n/a"
    print(f"=== DONE mean={mean_text} saved {out_dir / 'summary.json'} ===", flush=True)


if __name__ == "__main__":
    main()
